--create a new database. 
CREATE DATABASE C6_R5;

-- execute a configuration change 
-- so that for the following steps Snowflake does not use caching for the sesion
ALTER SESSION SET USE_CACHED_RESULT=FALSE; 

--create a simple table called SENSOR_DATA to hold demo data
CREATE OR REPLACE TABLE SENSOR_DATA(
   CREATE_TS BIGINT,
   SENSOR_ID BIGINT,
   SENSOR_READING INTEGER
);


--insert demo data into the table.
INSERT INTO SENSOR_DATA
SELECT
    (SEQ8())::BIGINT AS CREATE_TS
    ,UNIFORM(1,9999999,RANDOM(11111))::BIGINT SENSOR_ID
    ,UNIFORM(1,9999999,RANDOM(22222))::INTEGER SENSOR_READING
FROM TABLE(GENERATOR(ROWCOUNT => 1000000000))
ORDER BY CREATE_TS;


-- change clustering on create_ts
ALTER TABLE SENSOR_DATA  CLUSTER BY (CREATE_TS);

--run a couple of queries on each of the columns
SELECT 
COUNT(*) CNT
,AVG(SENSOR_READING) MEAN_SENSOR_READING
FROM SENSOR_DATA WHERE CREATE_TS 
BETWEEN 100000000 AND 100001000;
 
SELECT 
COUNT(*) CNT, 
AVG(SENSOR_READING)  MEAN_SENSOR_READING 
FROM SENSOR_DATA 
WHERE SENSOR_ID BETWEEN 100000 AND 101000;
 
--create a materialized view
CREATE OR REPLACE MATERIALIZED VIEW MV_SENSOR_READING(CREATE_TS, SENSOR_ID, SENSOR_READING) 
CLUSTER BY (SENSOR_ID) AS
SELECT CREATE_TS, SENSOR_ID, SENSOR_READING
FROM SENSOR_DATA;


--rerun the second query in step 6 that did not perform well before. 
--we should see a reduction in execution time
SELECT COUNT(*) CNT, AVG(SENSOR_READING)  MEAN_SENSOR_READING 
FROM MV_SENSOR_READING 
WHERE SENSOR_ID BETWEEN 100000 AND 101000;